### ISSUE TITLE
Registration - Database and Linking

### ISSUE THREAD

**Issue by jato8987** [jato8987/CC_project#4]

**Comment by mash4375** [comment]
I set up an AWS instance of a Postgresql database.
This is the command to access by mac terminal:
psql -h fortedb.cfsvavbwa9qq.us-east-2.rds.amazonaws.com -p 5432 -U fortemaster forte

host: fortedb.cfsvavbwa9qq.us-east-2.rds.amazonaws.com
port: 5432
username: fortemaster
password: Paradise1!
db_name: forte

Can someone else try accessing it to make sure this works?

**Comment by saev9307** [comment]
@mash4375 I just committed the SQL code to make the Database tables, put sample data into them, and run some test queries. Maybe put add the model to your DB and tomorrow I can try and access it from my computer.

**Comment by mash4375** [comment]
@saev9307 I added your data to the database and linked to it in the homepage. It worked flawlessly.

**Comment by jato8987** [comment]
Completed.
